"use client";
import { useState } from "react";
import { Check, Fish } from "./icons";

export function SubmissionForm({ configured }: { configured: boolean }) {
  const [state, setState] = useState<"idle" | "sending" | "sent" | "error">("idle");
  const [message, setMessage] = useState("");
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setState("sending"); const body = new FormData(e.currentTarget); const response = await fetch("/api/submissions", { method: "POST", body }); const result = await response.json(); if (response.ok) setState("sent"); else { setState("error"); setMessage(result.error || "Unable to submit this catch."); } }
  if (state === "sent") return <div className="form-success"><span><Check /></span><h2>Catch sent for review</h2><p>An admin will review the details and photo before it appears in the family record book.</p></div>;
  return <form className="submission-form" onSubmit={submit}><div className="form-intro"><Fish /><div><h1>Submit a new catch</h1><p>Share the details while the memory is fresh. An admin will review your submission before it goes live.</p></div></div>{!configured && <div className="setup-notice"><strong>Preview mode:</strong> connect Supabase environment variables to enable authenticated submissions.</div>}<fieldset><legend>About the catch</legend><div className="form-grid"><label>Fish species *<input name="species" required /></label><label>Angler *<input name="angler" required /></label><label>Date caught *<input type="date" name="date" required /></label><label>Water body *<input name="water" required /></label><label>Length (inches)<input type="number" name="length" min="0" step="0.01" /></label><label>Weight (pounds)<input type="number" name="weight" min="0" step="0.01" /></label><label>City<input name="city" /></label><label>State / region<input name="state" /></label><label className="wide">Bait, lure, or method<input name="caughtWith" /></label></div></fieldset><fieldset><legend>Location & memory</legend><div className="form-grid"><label>Latitude<input type="number" name="lat" min="-90" max="90" step="any" /></label><label>Longitude<input type="number" name="lng" min="-180" max="180" step="any" /></label><label className="wide">The story<textarea name="story" rows={6} placeholder="Where were you, who was there, and how did the catch happen?" /></label><label className="wide photo-input">Catch photo<input name="photo" type="file" accept="image/jpeg,image/png,image/webp,image/gif" /></label></div></fieldset>{state === "error" && <p className="form-error">{message}</p>}<button className="primary-button" disabled={state === "sending" || !configured}>{state === "sending" ? "Sending…" : "Send for approval"}</button></form>;
}
